-- ============================================================
-- 0025: worker notifications.
--
-- Four kinds, all written into `notifications` (the app reads them and
-- Expo push delivers them):
--
--   shift_soon   15 min before shift start — a nudge, sent to everyone
--                on shift who has not yet arrived
--   late         15 min after shift start — only if still not checked in
--   checkout_due 15 min after shift end — only if still checked in
--   advance      the moment the owner approves or rejects a request
--
-- Reminders are generated by a pg_cron job that runs every 5 minutes
-- and works out who is due. Doing this server-side rather than with
-- local phone alarms means the message reflects what the system
-- actually knows — someone who has already punched is never told to
-- check in.
--
-- A unique index makes each (worker, day, kind) message send once, so
-- a re-run of the job cannot spam anyone.
-- ============================================================

alter table notifications
  add column if not exists for_date date,
  add column if not exists sent_push boolean not null default false;

create unique index if not exists idx_notif_once
  on notifications (profile_id, type, for_date)
  where for_date is not null;

-- where to deliver: one Expo push token per worker device
alter table profiles
  add column if not exists push_token text;

-- ---------- reminder generator ----------
create or replace function fn_queue_shift_reminders()
returns integer
language plpgsql security definer set search_path = public, pg_temp as
$$
declare
  v_today   date := (now() at time zone 'Asia/Kolkata')::date;
  v_now     time := (now() at time zone 'Asia/Kolkata')::time;
  v_grace   integer := fn_setting_int('shift_grace_minutes', 15);
  r         record;
  v_start   time;
  v_end     time;
  v_made    integer := 0;
  v_punches integer;
  v_open    boolean;
begin
  for r in
    select p.id, p.full_name, p.shift_start, p.shift_end
    from profiles p
    where p.role = 'worker' and p.active and p.shift_start is not null
  loop
    select es.shift_start, es.shift_end into v_start, v_end
    from fn_effective_shift(r.id, v_today) es;
    if v_start is null then continue; end if;

    select count(*) into v_punches
    from attendance_app
    where profile_id = r.id and fn_ist_date(server_ts) = v_today;

    -- still on the floor: has punched in and not yet departed
    select v_punches > 0 and not exists (
      select 1 from attendance_app
      where profile_id = r.id and fn_ist_date(server_ts) = v_today
        and punch_kind = 'DEPARTURE'
    ) into v_open;

    -- 1. shift about to start (window: grace minutes before)
    if v_punches = 0
       and v_now between (v_start - make_interval(mins => v_grace)) and v_start then
      insert into notifications (profile_id, title, body, type, for_date)
      values (
        r.id,
        'Your shift starts soon',
        'Your shift starts at ' || to_char(v_start, 'FMHH12:MI am') ||
          '. Open the app and check in when you reach the shop.',
        'shift_soon', v_today
      )
      on conflict do nothing;
      v_made := v_made + 1;
    end if;

    -- 2. started, still no check-in
    if v_punches = 0
       and v_now between (v_start + make_interval(mins => v_grace))
                     and (v_start + make_interval(mins => v_grace + 10)) then
      insert into notifications (profile_id, title, body, type, for_date)
      values (
        r.id,
        'You have not checked in yet',
        'Your shift began at ' || to_char(v_start, 'FMHH12:MI am') ||
          '. Please check in now — later check-ins are sent to the owner for approval.',
        'late', v_today
      )
      on conflict do nothing;
      v_made := v_made + 1;
    end if;

    -- 3. shift over, still checked in
    if v_end is not null and v_open
       and v_now between (v_end + make_interval(mins => v_grace))
                     and (v_end + make_interval(mins => v_grace + 10)) then
      insert into notifications (profile_id, title, body, type, for_date)
      values (
        r.id,
        'Remember to check out',
        'Your shift ended at ' || to_char(v_end, 'FMHH12:MI am') ||
          '. Please check out so your hours are recorded correctly.',
        'checkout_due', v_today
      )
      on conflict do nothing;
      v_made := v_made + 1;
    end if;
  end loop;

  return v_made;
end;
$$;

revoke all on function fn_queue_shift_reminders() from public, anon, authenticated;

-- ---------- tell the worker when an advance is decided ----------
create or replace function fn_notify_advance_decision()
returns trigger
language plpgsql security definer set search_path = public, pg_temp as
$$
begin
  if new.status is distinct from old.status
     and new.status in ('APPROVED', 'REJECTED') then
    insert into notifications (profile_id, title, body, type)
    values (
      new.profile_id,
      case when new.status = 'APPROVED'
           then 'Advance approved'
           else 'Advance not approved' end,
      case when new.status = 'APPROVED'
           then 'The owner approved your advance of Rs. ' || trim(to_char(new.amount, 'FM999999')) ||
                '. It will be adjusted from your coming salary.'
           else 'The owner could not approve your advance of Rs. ' || trim(to_char(new.amount, 'FM999999')) ||
                ' this time. Please speak to them if you need to.' end,
      'advance'
    );
  end if;
  return new;
end;
$$;

drop trigger if exists notify_advance_decision on advances;
create trigger notify_advance_decision
  after update on advances
  for each row execute function fn_notify_advance_decision();

revoke all on function fn_notify_advance_decision() from public, anon, authenticated;

-- ---------- schedule: every 5 minutes ----------
do $$
begin
  perform cron.schedule(
    'shift-reminders',
    '*/5 * * * *',
    $job$ select fn_queue_shift_reminders() $job$
  );
exception when others then
  raise notice 'pg_cron unavailable — schedule fn_queue_shift_reminders() manually';
end
$$;
